server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: sky-pivot
  config:
    import: optional:file:/usr/local/etc/sky-pivot/application.properties

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized
      probes:
        enabled: true
